# Interactive Data Labeling Tool (Binary Classification)

Use this notebook to manually label posts as Reliable (1) or Unreliable (0) per the annotation rubric.

**Instructions:**
1. Run Cell 1 to load your unlabeled data.
2. Run Cell 2 to review label definitions and the rubric.
3. Run Cell 3 to start the interactive labeling session.
4. For each post, apply the **Strict Binary Classification** rubric to assign 1 (Reliable) or 0 (Unreliable).
5. Run Cell 4 to save your progress.
6. Run Cell 5 to merge with any previously labeled data.

## 1. Load Raw Data

In [7]:
import pandas as pd
from pathlib import Path
from datetime import datetime
import warnings
import os
warnings.filterwarnings('ignore')

# Detect environment and find CSV file.
# Priority: most recent labeled batch (resume) -> multi-source training CSV -> x fetch CSV.
search_roots = [
    Path('./ml/data'),
    Path('../data'),
    Path('../../ml/data'),
]

resume_candidates = []
for root in search_roots:
    if root.exists():
        resume_candidates.extend(root.glob('x_labeled_batch_*.csv'))

resume_candidates = sorted(
    resume_candidates,
    key=lambda p: p.stat().st_mtime,
    reverse=True,
)

possible_paths = [
    str(resume_candidates[0]) if resume_candidates else None,
    './ml/data/x_multi_source_training.csv',
    '../data/x_multi_source_training.csv',
    '../../ml/data/x_multi_source_training.csv',
    './ml/outputs/x_fetch/x_recent_posts_translated.csv',
    '/content/drive/MyDrive/x_multi_source_training.csv',  # Colab
]

CSV_PATH = None
for path in possible_paths:
    if path and Path(path).exists():
        CSV_PATH = Path(path)
        print(f'Found data at: {CSV_PATH}')
        break

if CSV_PATH is None:
    print('Data file not found in expected locations.')
    print('Please provide the full path to your CSV file.')
    csv_input = input('Path: ').strip()
    CSV_PATH = Path(csv_input)
    if not CSV_PATH.exists():
        raise FileNotFoundError(f'File not found: {csv_input}')

df = pd.read_csv(CSV_PATH)

# Normalize common schema differences
if 'x_post_id' in df.columns and 'post_id' not in df.columns:
    df = df.rename(columns={'x_post_id': 'post_id'})

for col in ['post_id', 'created_at', 'raw_text']:
    if col not in df.columns:
        raise ValueError(f"Missing required column: {col}")

if 'translated_text' not in df.columns:
    df['translated_text'] = df['raw_text']

if 'source_type' not in df.columns:
    df['source_type'] = 'social_media'

if 'source_file' not in df.columns:
    df['source_file'] = ''

if 'reliability_label' not in df.columns:
    df['reliability_label'] = pd.NA
if 'annotator_name' not in df.columns:
    df['annotator_name'] = ''
if 'annotation_time' not in df.columns:
    df['annotation_time'] = pd.NA
if 'notes' not in df.columns:
    df['notes'] = ''

print(f'Loaded {len(df)} posts')
print(f'Columns: {list(df.columns)}')
print('Source distribution:')
print(df['source_type'].value_counts(dropna=False))

df.head()

Found data at: ..\data\x_labeled_batch_20260511_1852_auto_bootstrap.csv
Loaded 210 posts
Columns: ['post_id', 'created_at', 'lang', 'raw_text', 'translated_text', 'source_type', 'source_file', 'reliability_label', 'annotator_name', 'annotation_time', 'notes']
Source distribution:
source_type
social_media    198
gdelt            12
Name: count, dtype: int64

,post_id,created_at,lang,raw_text,translated_text,source_type,source_file,reliability_label,annotator_name,annotation_time,notes
0,gdelt_0,20260511T050000Z,en,"[GDELT] In new signature drive , Filipino Chur...","[GDELT] In new signature drive , Filipino Chur...",gdelt,NaN,0.0,auto_bootstrap,2026-05-11T18:52:18,auto: gdelt non-traffic context
1,gdelt_1,20260510T101500Z,en,[GDELT] VinFast VF6 proves EVs go further deli...,[GDELT] VinFast VF6 proves EVs go further deli...,gdelt,NaN,NaN,NaN,NaN,NaN
2,gdelt_2,20260510T073000Z,en,[GDELT] [ Time Trowel ] What happens when we r...,[GDELT] [ Time Trowel ] What happens when we r...,gdelt,NaN,0.0,auto_bootstrap,2026-05-11T18:52:18,auto: gdelt non-traffic context
3,gdelt_3,20260509T213000Z,en,"[GDELT] Successful ASEAN Summit , a wow moment...","[GDELT] Successful ASEAN Summit , a wow moment...",gdelt,NaN,0.0,auto_bootstrap,2026-05-11T18:52:18,auto: gdelt non-traffic context
4,gdelt_4,20260509T063000Z,en,[GDELT] Quezon City roads closed Sunday for ru...,[GDELT] Quezon City roads closed Sunday for ru...,gdelt,NaN,1.0,auto_bootstrap,2026-05-11T18:52:18,auto: gdelt traffic/event + PH location

## 2. Interactive Labeling Session

In [8]:
# Prepare labeling dataframe (resume-safe for existing labels)
label_df = df[[
    'post_id',
    'created_at',
    'raw_text',
    'translated_text',
    'source_type',
    'source_file',
    'reliability_label',
    'annotator_name',
    'annotation_time',
    'notes',
]].copy()

label_df['reliability_label'] = pd.to_numeric(label_df['reliability_label'], errors='coerce')
label_df['annotator_name'] = label_df['annotator_name'].fillna('').astype(str)
label_df['notes'] = label_df['notes'].fillna('').astype(str)

# Annotation controls
ANNOTATION_LIMIT = 80  # set to None to label all pending rows
PREFER_RECENT_FIRST = True

if PREFER_RECENT_FIRST:
    label_df = label_df.sort_values('created_at', ascending=False).reset_index(drop=True)

pending_mask = label_df['reliability_label'].isna()
pending_total = int(pending_mask.sum())

if ANNOTATION_LIMIT is not None:
    pending_indices = label_df[pending_mask].head(ANNOTATION_LIMIT).index.tolist()
else:
    pending_indices = label_df[pending_mask].index.tolist()

print(f'Total rows: {len(label_df)}')
print(f'Already labeled: {len(label_df) - pending_total}')
print(f'Pending labels: {pending_total}')
print(f'Current annotation queue: {len(pending_indices)} posts')
print()
print('Queue source breakdown:')
print(label_df.loc[pending_indices, 'source_type'].value_counts(dropna=False))
print()
print('=' * 80)
print('STRICT BINARY CLASSIFICATION RUBRIC')
print('=' * 80)
print()
print('reliability_label: 1 = Reliable | 0 = Unreliable')
print()
print('1 = RELIABLE:')
print('   The text contains trustworthy, factual, and actionable information')
print('   regarding a traffic-disrupting event with specific geographic details.')
print()
print('0 = UNRELIABLE:')
print('   The text is misinformation, subjective noise, irrelevant, or non-specific.')
print()
print('ANNOTATION RULES BY SOURCE:')
print('  - Institutional sources (MMDA, PNP, PAGASA, News API): provisional 1 if event is specific')
print('  - GDELT data: evaluate relevance and local context; do not auto-score as reliable')
print('  - Commuter posts: 1 only if objective report with location + incident type')
print('  - Taglish/informal: evaluate semantics, not style')
print()
print('=' * 80)
print()
print('Run the next cell to begin interactive labeling.')

Total rows: 210
Already labeled: 163
Pending labels: 47
Current annotation queue: 47 posts

Queue source breakdown:
source_type
social_media    40
gdelt            7
Name: count, dtype: int64

================================================================================
STRICT BINARY CLASSIFICATION RUBRIC
================================================================================

reliability_label: 1 = Reliable | 0 = Unreliable

1 = RELIABLE:
   The text contains trustworthy, factual, and actionable information
   regarding a traffic-disrupting event with specific geographic details.

0 = UNRELIABLE:
   The text is misinformation, subjective noise, irrelevant, or non-specific.

ANNOTATION RULES BY SOURCE:
  - Institutional sources (MMDA, PNP, PAGASA, News API): provisional 1 if event is specific
  - GDELT data: evaluate relevance and local context; do not auto-score as reliable
  - Commuter posts: 1 only if objective report with location + incident type
  - Taglish/informal: evaluate semantics, not style

================================================================================

Run the next cell to begin interactive labeling.

In [12]:
# Interactive labeling loop - Strict Binary Classification
annotator = input('Enter your name for annotation: ').strip()
if not annotator:
    annotator = 'annotator'

labeled_count = 0
skipped_count = 0

for i, idx in enumerate(pending_indices, start=1):
    row = label_df.loc[idx]

    print(f'\n--- POST {i}/{len(pending_indices)} ---')
    print(f"ID: {row['post_id']}")
    print(f"Time: {row['created_at']}")
    print(f"Source: {row['source_type']}")

    if str(row.get('source_file', '')).strip():
        print(f"Source file: {row['source_file']}")

    print()
    print('RAW TEXT:')
    raw_text = str(row['raw_text'])
    raw_display = raw_text if raw_text and raw_text.lower() != 'nan' else '[missing raw text]'
    print(f"  {raw_display[:350]}..." if len(raw_display) > 350 else f"  {raw_display}")

    print()
    print('TRANSLATED TEXT:')
    translated_value = row.get('translated_text', '')
    translated_text = '' if pd.isna(translated_value) else str(translated_value)
    translated_display = translated_text if translated_text and translated_text.lower() != 'nan' else raw_display
    print(f"  {translated_display[:350]}..." if len(translated_display) > 350 else f"  {translated_display}")
    print()

    while True:
        rel_input = input('Reliable? (1=yes, 0=no, skip=skip, quit=save and stop): ').strip().lower()

        if rel_input == 'skip':
            skipped_count += 1
            break

        if rel_input == 'quit':
            print('Stopping early. You can save in the next cell.')
            i = len(pending_indices)
            break

        if rel_input in {'0', '1'}:
            reliability_label = int(rel_input)
            notes = input('Notes (optional): ').strip()

            label_df.loc[idx, 'reliability_label'] = reliability_label
            label_df.loc[idx, 'annotator_name'] = annotator
            label_df.loc[idx, 'annotation_time'] = pd.Timestamp.now().isoformat(timespec='seconds')
            label_df.loc[idx, 'notes'] = notes
            labeled_count += 1
            break

        print('  Invalid. Enter 1, 0, skip, or quit.')

    if rel_input == 'quit':
        break

    if (labeled_count + skipped_count) % 10 == 0:
        print(f"  [Progress: {labeled_count} labeled, {skipped_count} skipped]")

print('\n=== LABELING SESSION COMPLETE ===')
print(f'Total newly labeled this session: {labeled_count}')
print(f'Total skipped this session: {skipped_count}')
print(f'Total labeled in dataframe: {int(label_df["reliability_label"].notna().sum())}/{len(label_df)}')
print(f'Reliable (1): {int((label_df["reliability_label"] == 1).sum())}')
print(f'Unreliable (0): {int((label_df["reliability_label"] == 0).sum())}')

--- POST 1/47 ---
ID: gdelt_1
Time: 20260510T101500Z
Source: gdelt
Source file: nan

RAW TEXT:
  [GDELT] VinFast VF6 proves EVs go further delivers real - world performance beyond city driving (Source: https://gadgetsmagazine.com.ph/mobility/cars/vinfast-vf6-evs-go-further)

TRANSLATED TEXT:
  [GDELT] VinFast VF6 proves EVs go further delivers real - world performance beyond city driving (Source: https://gadgetsmagazine.com.ph/mobility/cars/vinfast-vf6-evs-go-further)


--- POST 2/47 ---
ID: gdelt_5
Time: 20260508T203000Z
Source: gdelt
Source file: nan

RAW TEXT:
  [GDELT] Fireworks memorial returns to honour Tyendinaga fishermen and keep questions alive (Source: https://theturtleislandnews.com/index.php/2026/05/08/fireworks-memorial-returns-to-honour-tyendinaga-fishermen-and-keep-questions-alive/)

TRANSLATED TEXT:
  [GDELT] Fireworks memorial returns to honour Tyendinaga fishermen and keep questions alive (Source: https://theturtleislandnews.com/index.php/2026/05/08/fireworks-memorial-returns-to-honour-tyendinaga-fishermen-and-keep-questions-alive/)


--- POST 3/47 ---
ID: gdelt_6
Time: 20260508T194500Z
Source: gdelt
Source file: nan

RAW TEXT:
  [GDELT] Signature Series starts Susana Heights transformation (Source: http://www.shangbao.com.ph/jjxw/2026/05-08/197998.shtml)

TRANSLATED TEXT:
  [GDELT] Signature Series starts Susana Heights transformation (Source: http://www.shangbao.com.ph/jjxw/2026/05-08/197998.shtml)


--- POST 4/47 ---
ID: gdelt_7
Time: 20260508T183000Z
Source: gdelt
Source file: nan

RAW TEXT:
  [GDELT] Fireworks memorial returns to honour Tyendinaga fishermen and keep questions alive (Source: https://www.wellandtribune.ca/news/canada/fireworks-memorial-returns-to-honour-tyendinaga-fishermen-and-keep-questions-alive/article_91ff743b-786f-5ec3-a8eb-1b3f28eae64a.html)

TRANSLATED TEXT:
  [GDELT] Fireworks memorial returns to honour Tyendinaga fishermen and keep questions alive (Source: https://www.wellandtribune.ca/news/canada/fireworks-memorial-returns-to-honour-tyendinaga-fishermen-and-keep-questions-alive/article_91ff743b-786f-5ec3-a8eb-1b3f28eae64a.html)


--- POST 5/47 ---
ID: gdelt_9
Time: 20260508T154500Z
Source: gdelt
Source file: nan

RAW TEXT:
  [GDELT] Garden City Skyway twinning project ramping up (Source: https://www.stcatharinesstandard.ca/news/niagara-region/garden-city-skyway-twinning-construction-details/article_d0ba19df-c6ca-59b1-a126-f9132b6f3135.html)

TRANSLATED TEXT:
  [GDELT] Garden City Skyway twinning project ramping up (Source: https://www.stcatharinesstandard.ca/news/niagara-region/garden-city-skyway-twinning-construction-details/article_d0ba19df-c6ca-59b1-a126-f9132b6f3135.html)


--- POST 6/47 ---
ID: gdelt_10
Time: 20260508T124500Z
Source: gdelt
Source file: nan

RAW TEXT:
  [GDELT] Garden City Skyway twinning project ramping up (Source: https://www.niagarafallsreview.ca/news/niagara-region/garden-city-skyway-twinning-construction-details/article_1ee46b85-c2b6-59c7-b927-15a31dec70dc.html)

TRANSLATED TEXT:
  [GDELT] Garden City Skyway twinning project ramping up (Source: https://www.niagarafallsreview.ca/news/niagara-region/garden-city-skyway-twinning-construction-details/article_1ee46b85-c2b6-59c7-b927-15a31dec70dc.html)


--- POST 7/47 ---
ID: gdelt_11
Time: 20260508T113000Z
Source: gdelt
Source file: nan

RAW TEXT:
  [GDELT] How Corruption Exacerbates the Climate Crisis in the Philippines (Source: https://thediplomat.com/2026/05/how-corruption-exacerbates-the-climate-crisis-in-the-philippines/)

TRANSLATED TEXT:
  [GDELT] How Corruption Exacerbates the Climate Crisis in the Philippines (Source: https://thediplomat.com/2026/05/how-corruption-exacerbates-the-climate-crisis-in-the-philippines/)


--- POST 8/47 ---
ID: 2053758841855316472
Time: 2026-05-11T08:47:19.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  @sangeeta2599 Mmda bus stop i m waiting

TRANSLATED TEXT:
  @sangeeta2599 Mmda bus stop i m waiting


--- POST 9/47 ---
ID: 2053643549930148011
Time: 2026-05-11T01:09:11.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  🚗 C5 Coding Hours in Metro Manila 🇵🇭

🕖 Morning: 7AM–10AM
🕔 Evening: 5PM–8PM
✅ Window Hours: 10:01AM–4:59PM
📌 No Coding on Weekends &amp; Holidays

Avoid traffic violations and stay updated with MMDA rules. 🚦
🌐 https://t.co/RJE4C3IE8c

#C5 #CodingHours #MMDA #TrafficUpdate https://t.co/ahppZedxzz

TRANSLATED TEXT:
  🚗 C5 Coding Hours in Metro Manila 🇵🇭

🕖 Morning: 7AM–10AM
🕔 Evening: 5PM–8PM
✅ Window Hours: 10:01AM–4:59PM
📌 No Coding on Weekends &amp; Holidays

Avoid traffic violations and stay updated with MMDA rules. 🚦
🌐 https://t.co/RJE4C3IE8c

#C5 #CodingHours #MMDA #TrafficUpdate https://t.co/ahppZedxzz


--- POST 10/47 ---
ID: 2053459875535966497
Time: 2026-05-10T12:59:20.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  @freakonaomics Magic Mushrooms and Amphetamines and MMDA from Myristicin

TRANSLATED TEXT:
  @freakonaomics Magic Mushrooms and Amphetamines and MMDA from Myristicin

  [Progress: 10 labeled, 0 skipped]

--- POST 11/47 ---
ID: 2053437156375535659
Time: 2026-05-10T11:29:03.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  @MMDA @MMDAtweets would like to report illegal parking for patrons of Choir garden along the length of Annapolis at, San Juan, MABUHAY LANE https://t.co/lZm9Cp6myX

TRANSLATED TEXT:
  @MMDA @MMDAtweets would like to report illegal parking for patrons of Choir garden along the length of Annapolis at, San Juan, MABUHAY LANE https://t.co/lZm9Cp6myX


--- POST 12/47 ---
ID: 2053351711029473455
Time: 2026-05-10T05:49:31.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  Your bicycle lanes are useless. 2026 May 11 1pm, majority of said lanes are occupied by cars illegally parked around Annapolis, Missouri, Connecticut with “No Parking” signs in plain sight and enforcers doing nothing. What a joke. @franciszamora30 @sanjuancityncr @MMDA

TRANSLATED TEXT:
  Your bicycle lanes are useless. 2026 May 11 1pm, majority of said lanes are occupied by cars illegally parked around Annapolis, Missouri, Connecticut with “No Parking” signs in plain sight and enforcers doing nothing. What a joke. @franciszamora30 @sanjuancityncr @MMDA


--- POST 13/47 ---
ID: 2053299330338214047
Time: 2026-05-10T02:21:23.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  @RadioGenoa @govphOfficial @zerowastephl @MMDA @govphOfficial @Official_DILG @PHcities Phils catching up to Indonesia in waste problems

TRANSLATED TEXT:
  @RadioGenoa @govphOfficial @zerowastephl @MMDA @govphOfficial @Official_DILG @PHcities Phils catching up to Indonesia in waste problems


--- POST 14/47 ---
ID: 2053285288873746527
Time: 2026-05-10T01:25:35.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  🚗 Pasay Coding Hours 2025 🇵🇭

🕖 Coding Hours:
7AM–10AM
5PM–8PM
✅ Window Hours: 10:01AM–4:59PM
📌 No Coding on Weekends
💰 Fine: ₱300–₱500
Stay updated with MMDA traffic rules and avoid violations. 🚦

🌐 https://t.co/Fvy4bk2hO7
#Pasay #CodingHours #MMDA #TrafficUpdate

TRANSLATED TEXT:
  🚗 Pasay Coding Hours 2025 🇵🇭

🕖 Coding Hours:
7AM–10AM
5PM–8PM
✅ Window Hours: 10:01AM–4:59PM
📌 No Coding on Weekends
💰 Fine: ₱300–₱500
Stay updated with MMDA traffic rules and avoid violations. 🚦

🌐 https://t.co/Fvy4bk2hO7
#Pasay #CodingHours #MMDA #TrafficUpdate


--- POST 15/47 ---
ID: 2053235081959895530
Time: 2026-05-09T22:06:05.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  CHUGGING WATER TO SOBER MYSELF UP SO THAT MMDA MAKES FULL EFFECT #youngho

TRANSLATED TEXT:
  CHUGGING WATER TO SOBER MYSELF UP SO THAT MMDA MAKES FULL EFFECT #youngho


--- POST 16/47 ---
ID: 2053145768916394003
Time: 2026-05-09T16:11:11.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  @MMDA Thank you 😊.  This is very much appreciated. Traffic has eased up, and much better than before.
Maybe because cars have lessen due t high gasoliine cost

TRANSLATED TEXT:
  @MMDA Thank you 😊.  This is very much appreciated. Traffic has eased up, and much better than before.
Maybe because cars have lessen due t high gasoliine cost


--- POST 17/47 ---
ID: 2053058471864733847
Time: 2026-05-09T10:24:18.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  FIRE ALERT: As of 6:06 PM. Ongoing fire incident at Gatchalian-1, Brgy. San Dionisio, Paranaque City involving a residential area. Now on its 2nd alarm. Firefighters on site. #mmda

TRANSLATED TEXT:
  FIRE ALERT: As of 6:06 PM. Ongoing fire incident at Gatchalian-1, Brgy. San Dionisio, Paranaque City involving a residential area. Now on its 2nd alarm. Firefighters on site. #mmda


--- POST 18/47 ---
ID: 2053046956868681953
Time: 2026-05-09T09:38:32.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  @TANGEDCO_Offcl no power supply for the past 3 hrs in MMDA colony, Arumbakkam. Kindly rectify the issue at the earliest.

TRANSLATED TEXT:
  @TANGEDCO_Offcl no power supply for the past 3 hrs in MMDA colony, Arumbakkam. Kindly rectify the issue at the earliest.


--- POST 19/47 ---
ID: 2052950981001056604
Time: 2026-05-09T03:17:10.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  @TANGEDCO_Offcl No Power in Mmda , Mathur , Madhavaram from Morning 5am. Pls Rectify the issue as soon as possible

TRANSLATED TEXT:
  @TANGEDCO_Offcl No Power in Mmda , Mathur , Madhavaram from Morning 5am. Pls Rectify the issue as soon as possible


--- POST 20/47 ---
ID: 2052946930490077296
Time: 2026-05-09T03:01:04.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  🇵🇭 A threat actor has allegedly leaked employee PII and payroll-related data associated with the Metropolitan Manila Development Authority (MMDA) on a cybercrime forum.

According to the post, the exposed information reportedly includes sensitive employee-related records and https://t.co/V1mv5mJkjD

TRANSLATED TEXT:
  🇵🇭 A threat actor has allegedly leaked employee PII and payroll-related data associated with the Metropolitan Manila Development Authority (MMDA) on a cybercrime forum.

According to the post, the exposed information reportedly includes sensitive employee-related records and https://t.co/V1mv5mJkjD

  [Progress: 20 labeled, 0 skipped]

--- POST 21/47 ---
ID: 2052919943016923138
Time: 2026-05-09T01:13:50.000Z
Source: social_media
Source file: x_recent_posts_translated_20260511_1657.csv

RAW TEXT:
  @TVKMLPRABHU  Congrats Prabhu for elected as MLA for Madhavaram .
I am also from Mathur MMDA but Settled in US.

Congrats to you.. best of luck.

TRANSLATED TEXT:
  @TVKMLPRABHU  Congrats Prabhu for elected as MLA for Madhavaram .
I am also from Mathur MMDA but Settled in US.

Congrats to you.. best of luck.


--- POST 22/47 ---
ID: 2052056992550953330
Time: 2026-05-06T16:04:47.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  plus i got stopped by an mmda last night because i made a wrong turn. sorry po. https://t.co/xGrQ3w4YPw

TRANSLATED TEXT:
  plus i got stopped by an mmda last night because i made a wrong turn. sorry po. https://t.co/xGrQ3w4YPw


--- POST 23/47 ---
ID: 2052037276734259481
Time: 2026-05-06T14:46:26.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  The fire that hit the sanitary landfill in Navotas City is now around 80% contained, the Metropolitan Manila Development Authority (MMDA) said Wednesday.

https://t.co/ufwuY3YdAP

TRANSLATED TEXT:
  The fire that hit the sanitary landfill in Navotas City is now around 80% contained, the Metropolitan Manila Development Authority (MMDA) said Wednesday.

https://t.co/ufwuY3YdAP


--- POST 24/47 ---
ID: 2052015731647406244
Time: 2026-05-06T13:20:49.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  MMDA Public Affairs Staff-Public Information Office is accepting applications for a WRITER.

Interested applicants may submit their personal data sheet (PDS), Transcript of Records, and application letter to paspiohiring@gmail.com until MAY 15, 2026.

Use the job title as the https://t.co/bbj0S5znJ9

TRANSLATED TEXT:
  (ORG_3> is accepting applications for a WRITER. Interested actoricants with matching personal data sheet (PDS), Trancripts of <MIC_1>, and application letter to <ORG_0h>ring.comLA 15,26. Use the joint as the one


--- POST 25/47 ---
ID: 2052013687322374233
Time: 2026-05-06T13:12:42.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  MMDA chief and concurrent Metro Manila DRRMC head Don Artes said the fire at the Navotas Sanitary Landfill is around 80 percent contained, and efforts to completely put out the fire are ongoing.

https://t.co/zSZvip3heZ

TRANSLATED TEXT:
  MMDA chief and concurrent Metro Manila DRRMC head Don Artes said the fire at the Navotas Sanitary Landfill is around 80 percent contained, and efforts to completely put out the fire are ongoing.

https://t.co/zSZvip3heZ


--- POST 26/47 ---
ID: 2051979103679705443
Time: 2026-05-06T10:55:16.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  @Vincent2112_ @beachygirlplus Not only is he underage, he needs at least one term in a national position before presidency (example:  MMDA Chairperson; DILG secretary; Senator) as preparation for presidency.  From Mayor to President is a quantum leap.

TRANSLATED TEXT:
  @Vincent2112_ @beachygirlplus Not only is he underage, he needs at least one term in a national position before presidency (example:  MMDA Chairperson; DILG secretary; Senator) as preparation for presidency.  From Mayor to President is a quantum leap.


--- POST 27/47 ---
ID: 2051931751564624229
Time: 2026-05-06T07:47:07.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  The Metro Manila Disaster Risk Reduction and Management Council (MMDRRMC) convened today to provide a status update on the Navotas Sanitary Landfill fire incident, reporting that the fire is now 79.6% contained.

Read more: https://t.co/c6dEMMNjbX #mmda #mmdaatyourservice https://t.co/BttjDSl5OE

TRANSLATED TEXT:
  The Metro Manila Disaster Risk Reduction and Management Council (MMDRRMC) convened today to provide a status update on the Navotas Sanitary Landfill fire incident, reporting that the fire is now 79.6% contained.

Read more: https://t.co/c6dEMMNjbX #mmda #mmdaatyourservice https://t.co/BttjDSl5OE


--- POST 28/47 ---
ID: 2051930017639059842
Time: 2026-05-06T07:40:13.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  The fire that hit the sanitary landfill in Navotas City is now around 80% contained, the Metropolitan Manila Development Authority (MMDA) said on Wednesday.

READ: https://t.co/34EqErGUCf https://t.co/cOyoOtFS0P

TRANSLATED TEXT:
  The fire that hit the sanitary landfill in Navotas City is now around 80% contained, the Metropolitan Manila Development Authority (MMDA) said on Wednesday.

READ: https://t.co/34EqErGUCf https://t.co/cOyoOtFS0P


--- POST 29/47 ---
ID: 2051919459791847828
Time: 2026-05-06T06:58:16.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  @MMDA Taken May 6, 2026, ~12nn.

Illegal parking on both sides of the P. Tuazon Mabuhay Lane. https://t.co/IowflvGenz

TRANSLATED TEXT:
  @MMDA Taken May 6, 2026, ~12nn.

Illegal parking on both sides of the P. Tuazon Mabuhay Lane. https://t.co/IowflvGenz


--- POST 30/47 ---
ID: 2051912435251159425
Time: 2026-05-06T06:30:21.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  @RubiLiciousMe [Admin 18]
Good day,
Thank you for reaching out to the MMDA and for sharing your concerns regarding the request to reinstate the traffic signal at the Banawe Avenue–Quezon Avenue intersection. We appreciate you bringing this matter to our attention.

In response, the TEC

TRANSLATED TEXT:
  @RubiLiciousMe [Admin 18]
Good day,
Thank you for reaching out to the MMDA and for sharing your concerns regarding the request to reinstate the traffic signal at the Banawe Avenue–Quezon Avenue intersection. We appreciate you bringing this matter to our attention.

In response, the TEC

  [Progress: 30 labeled, 0 skipped]

--- POST 31/47 ---
ID: 2051911748840554808
Time: 2026-05-06T06:27:38.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  The fire that hit the sanitary landfill in Navotas City is now around 80% contained, the Metropolitan Manila Development Authority (MMDA) said Wednesday.

Read more:
https://t.co/34EqErGUCf

TRANSLATED TEXT:
  The fire that hit the sanitary landfill in Navotas City is now around 80% contained, the Metropolitan Manila Development Authority (MMDA) said Wednesday.

Read more:
https://t.co/34EqErGUCf


--- POST 32/47 ---
ID: 2051906846525698213
Time: 2026-05-06T06:08:09.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  MMDA Public Affairs Staff-Public Information Office is accepting applications for a WRITER.

Interested applicants may submit their personal data sheet (PDS), Transcript of Records, and application letter to paspiohiring@gmail.com until MAY 15, 2026.

Use the job title as the https://t.co/d4pkrFUr3b

TRANSLATED TEXT:
  (ORG_3> is accepting applications for a WRITER. Interested actoricants with matching personal data sheet (PDS), Trancripts of <MIC_1>, and application letter to <ORG_0h>ring.comLA 15,26. Use the joint as the one


--- POST 33/47 ---
ID: 2051876759801639312
Time: 2026-05-06T04:08:36.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  @MMDA @MMDA

Taken 12nn May 6, 2026.

Illegal parking on both sides of P. Tuazon Mabuhay Lane https://t.co/PWHiYAv3HF

TRANSLATED TEXT:
  @MMDA @MMDA

Taken 12nn May 6, 2026.

Illegal parking on both sides of P. Tuazon Mabuhay Lane https://t.co/PWHiYAv3HF


--- POST 34/47 ---
ID: 2051869356762816911
Time: 2026-05-06T03:39:11.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  ‘WAG MONG GINAGAMIT ‘YUNG RELIHIYON’

A Metropolitan Manila Development Authority (MMDA) road clearing operation along Taft Avenue in Pasay City went viral after a driver apprehended by authorities invoked religion during the arrest.

Read: https://t.co/f59jiDJHon https://t.co/FAkt9wGadI

TRANSLATED TEXT:
  ‘WAG MONG GINAGAMIT ‘YUNG RELIHIYON’

A Metropolitan Manila Development Authority (MMDA) road clearing operation along Taft Avenue in Pasay City went viral after a driver apprehended by authorities invoked religion during the arrest.

Read: https://t.co/f59jiDJHon https://t.co/FAkt9wGadI


--- POST 35/47 ---
ID: 2051853231069045148
Time: 2026-05-06T02:35:06.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:
  LOOK: Navotas Mayor John Rey Tiangco briefs the MMDA and other LGUs on efforts to extinguish the Navotas Sanitary Landfill fire, which has affected air quality in Metro Manila and Bulacan since it started last April 10. | via @andietagz https://t.co/eXvb6HARZU

TRANSLATED TEXT:
  LOOK: Navotas Mayor John Rey Tiangco briefs the MMDA and other LGUs on efforts to extinguish the Navotas Sanitary Landfill fire, which has affected air quality in Metro Manila and Bulacan since it started last April 10. | via @andietagz https://t.co/eXvb6HARZU


--- POST 36/47 ---
ID: 2051853010255667479
Time: 2026-05-06T02:34:13.000Z
Source: social_media
Source file: x_recent_posts_translated_20260506_1618.csv

RAW TEXT:

## 3. Save Labeled Data

In [13]:
# Save this batch
timestamp = datetime.now().strftime('%Y%m%d_%H%M')
batch_filename = f'x_labeled_batch_{timestamp}_{annotator}.csv'

# Determine save path (local first, fallback to Colab)
possible_save_dirs = [
    Path('./ml/data'),
    Path('../data'),
    Path('../../ml/data'),
    Path('/content/drive/MyDrive'),  # Colab
]

save_dir = None
for d in possible_save_dirs:
    try:
        d.mkdir(parents=True, exist_ok=True)
        save_dir = d
        break
    except:
        continue

if save_dir is None:
    save_dir = Path('./ml/data')
    save_dir.mkdir(parents=True, exist_ok=True)

save_path = save_dir / batch_filename
label_df.to_csv(save_path, index=False)
print(f'Saved to: {save_path}')

# Summary statistics
labeled = label_df[label_df['reliability_label'].notna()]
print('\nLabeled Summary:')
print(f'  Total labeled: {len(labeled)}')
print(f'  Reliable (1): {(labeled["reliability_label"] == 1).sum()}')
print(f'  Unreliable (0): {(labeled["reliability_label"] == 0).sum()}')
if len(labeled) > 0:
    print(f'  Reliability rate: {(labeled["reliability_label"] == 1).sum() / len(labeled) * 100:.1f}%')
else:
    print('  Reliability rate: N/A (no labels yet)')

Saved to: ml\data\x_labeled_batch_20260511_1934_Joshua Pagallaman.csv

Labeled Summary:
  Total labeled: 210
  Reliable (1): 168
  Unreliable (0): 42
  Reliability rate: 80.0%

## 4. Merge with Historical Labels (Optional)

In [14]:
# Load any existing labeled master file
possible_master_paths = [
    Path('./ml/data/x_labeled_master.csv'),
    Path('../data/x_labeled_master.csv'),
    Path('../../ml/data/x_labeled_master.csv'),
    Path('/content/drive/MyDrive/x_labeled_master.csv'),  # Colab
]

master_path = None
for p in possible_master_paths:
    if p.exists():
        master_path = p
        break

if master_path is None:
    # Default to local path
    master_path = Path('./ml/data/x_labeled_master.csv')

if master_path.exists():
    master_df = pd.read_csv(master_path)
    print(f'Loaded existing master with {len(master_df)} rows')
    
    # Merge: take labeled rows from current batch
    new_labeled = label_df[label_df['reliability_label'].notna()].copy()
    
    # Remove any duplicates in master (by post_id)
    master_df = master_df[~master_df['post_id'].isin(new_labeled['post_id'])]
    
    # Append and save
    merged = pd.concat([master_df, new_labeled], ignore_index=True)
    merged = merged.sort_values('created_at')
    
    # Ensure parent dir exists
    master_path.parent.mkdir(parents=True, exist_ok=True)
    merged.to_csv(master_path, index=False)
    
    print(f'Updated master now has {len(merged)} total labeled rows')
    print(f'  Reliable (1): {(merged["reliability_label"] == 1).sum()}')
    print(f'  Unreliable (0): {(merged["reliability_label"] == 0).sum()}')
    print(f'  Reliability rate: {(merged["reliability_label"] == 1).sum() / len(merged) * 100:.1f}%')
else:
    # Create new master from current batch
    new_labeled = label_df[label_df['reliability_label'].notna()].copy()
    
    # Ensure parent dir exists
    master_path.parent.mkdir(parents=True, exist_ok=True)
    new_labeled.to_csv(master_path, index=False)
    print(f'Created new master with {len(new_labeled)} labeled rows')
    print(f'  Reliable (1): {(new_labeled["reliability_label"] == 1).sum()}')
    print(f'  Unreliable (0): {(new_labeled["reliability_label"] == 0).sum()}')
    print(f'  Reliability rate: {(new_labeled["reliability_label"] == 1).sum() / len(new_labeled) * 100:.1f}%')

print(f'\nMaster saved to: {master_path}')

Created new master with 210 labeled rows
  Reliable (1): 168
  Unreliable (0): 42
  Reliability rate: 80.0%

Master saved to: ml\data\x_labeled_master.csv

## 5. Inspect Master Dataset

In [15]:
# Show summary of master labeled data
possible_master_paths = [
    Path('./ml/data/x_labeled_master.csv'),
    Path('../data/x_labeled_master.csv'),
    Path('../../ml/data/x_labeled_master.csv'),
    Path('/content/drive/MyDrive/x_labeled_master.csv'),  # Colab
]

master_path = None
for p in possible_master_paths:
    if p.exists():
        master_path = p
        break

if master_path and master_path.exists():
    master = pd.read_csv(master_path)
    print(f'Master dataset: {len(master)} labeled posts')
    print()
    print('Reliability distribution:')
    dist = master['reliability_label'].value_counts().sort_index()
    print(dist)
    print()
    reliable_count = (master['reliability_label'] == 1).sum()
    total_count = len(master)
    print(f'Reliability rate: {reliable_count}/{total_count} = {reliable_count/total_count*100:.1f}%')
    print()
    print('Sample of labeled data:')
    display(master[['post_id', 'created_at', 'reliability_label', 'annotator_name', 'notes']].head(10))
else:
    print('Master dataset not found yet. Run the labeling cells first.')

Master dataset: 210 labeled posts

Reliability distribution:
reliability_label
0.0     42
1.0    168
Name: count, dtype: int64

Reliability rate: 168/210 = 80.0%

Sample of labeled data:

,post_id,created_at,reliability_label,annotator_name,notes
0,gdelt_0,20260511T050000Z,0.0,auto_bootstrap,auto: gdelt non-traffic context
1,gdelt_1,20260510T101500Z,0.0,Joshua Pagallaman,Advertisement Post
2,gdelt_2,20260510T073000Z,0.0,auto_bootstrap,auto: gdelt non-traffic context
3,gdelt_3,20260509T213000Z,0.0,auto_bootstrap,auto: gdelt non-traffic context
4,gdelt_4,20260509T063000Z,1.0,auto_bootstrap,auto: gdelt traffic/event + PH location
5,gdelt_5,20260508T203000Z,0.0,Joshua Pagallaman,Not related to PH
6,gdelt_6,20260508T194500Z,0.0,Joshua Pagallaman,NaN
7,gdelt_7,20260508T183000Z,0.0,Joshua Pagallaman,Not related
8,gdelt_8,20260508T164500Z,0.0,auto_bootstrap,auto: gdelt non-traffic context
9,gdelt_9,20260508T154500Z,0.0,Joshua Pagallaman,Not in PH